services:
  - type: web
    name: rdv-medical
    runtime: image
    repo: https://github.com/mitiarj05/rdv_Medecin  # ⚠️ CORRIGÉ
    branch: amelioration2  # ⚠️ AJOUTEZ CELLE-CI
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        fromDatabase:
          name: rdv-medical-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: rdv-medical-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: rdv-medical-db
          property: password
      - key: MAIL_USERNAME
        value: mitiarj05@gmail.com
      - key: MAIL_PASSWORD
        value: flfz tyrh tpih pjsa
      - key: JDBC_DATABASE_URL
        fromDatabase:
          name: rdv-medical-db
          property: connectionString
      - key: JDBC_DATABASE_USERNAME
        fromDatabase:
          name: rdv-medical-db
          property: user
      - key: JDBC_DATABASE_PASSWORD
        fromDatabase:
          name: rdv-medical-db
          property: password

databases:
  - name: rdv-medical-db
    databaseName: rdv_medecin
    user: rdv_user
    plan: free