services:
  - type: web
    name: rdv-medical
    runtime: docker
    repo: https://github.com/mitiarj05/rdv_Medecin
    branch: amelioration2
    plan: free
    dockerfilePath: ./Dockerfile
    # Render injecte PORT automatiquement, Tomcat écoute sur 8080
    healthCheckPath: /test.html
    envVars:
      - key: MAIL_USERNAME
        sync: false          # À saisir manuellement dans le dashboard Render (secret)
      - key: MAIL_PASSWORD
        sync: false          # À saisir manuellement dans le dashboard Render (secret)
      - key: DB_URL
        fromDatabase:
          name: rdv-medical-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: rdv-medical-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: rdv-medical-db
          property: password

databases:
  - name: rdv-medical-db
    databaseName: rdv_medecin
    user: rdv_user
    plan: free
    postgresMajorVersion: 16