services:
  - type: web
    name: rdv-medical
    runtime: docker
    repo: https://github.com/mitiarj05/rdv_Medecin
    branch: amelioration2
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MAIL_USERNAME
        value: mitiarj05@gmail.com
      - key: MAIL_PASSWORD
        value: flfz tyrh tpih pjsa
      - key: DB_URL
        fromDatabase:
          name: rdv-medical-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: rdv-medical-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: rdv-medical-db
          property: password

databases:
  - name: rdv-medical-db
    databaseName: rdv_medecin
    user: rdv_user
    plan: free
    postgresMajorVersion: 16